name: Python CI
on:
  push:

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          Python-version: '3.12'
      
      - name: Run Application
        run: python app.py
        